import { Prefecture } from '../models/prefecture';

const allPrefObj: Record<Prefecture, any> = {
  北海道: null,
  青森県: null,
  岩手県: null,
  宮城県: null,
  秋田県: null,
  山形県: null,
  福島県: null,
  茨城県: null,
  栃木県: null,
  群馬県: null,
  埼玉県: null,
  千葉県: null,
  東京都: null,
  神奈川県: null,
  新潟県: null,
  富山県: null,
  石川県: null,
  福井県: null,
  山梨県: null,
  長野県: null,
  岐阜県: null,
  静岡県: null,
  愛知県: null,
  三重県: null,
  滋賀県: null,
  京都府: null,
  大阪府: null,
  兵庫県: null,
  奈良県: null,
  和歌山県: null,
  鳥取県: null,
  島根県: null,
  岡山県: null,
  広島県: null,
  山口県: null,
  徳島県: null,
  香川県: null,
  愛媛県: null,
  高知県: null,
  福岡県: null,
  佐賀県: null,
  長崎県: null,
  熊本県: null,
  大分県: null,
  宮崎県: null,
  鹿児島県: null,
  沖縄県: null,
};
export default allPrefObj;
